### ISSUE TITLE
MM wont start with Gestures enabled

### ISSUE THREAD

**Issue by truejp** [thobach/MMM-Gestures#27]
Hi,

I've tried a couple of things to fix this issue, but I am kinda stuck right there. I always get the following issue:

`[11.02.2023 21:18.30.223] [ERROR] Error: No native build was found for platform=linux arch=arm runtime=electron abi=110 uv=1 armv=default libc=glibc node=16.17.1 electron=22.0.0
    loaded from: /home/pi/MagicMirror/modules/MMM-Gestures/node_modules/@serialport/bindings-cpp `

On the previous installation, I tested a couple of things using node v16, so I thought the version was stored in some weird place. I just prepared a clean installation with the default MM installed using node v18.14.0, the error still stays the same. I wasn't able to find any hints with the stated node v16.17.1 so I honestly have no idea where this would come from. On this try I did not modify anything at all. Could you help point me in the right direction there?

Here's my Setup:
Raspberry Pi 4B
Arduino Nano (works perfectly fine)
Arduino IDE used for testing serial port
MagicMirror v2.22.0
Electron v22.0.0
Node v18.14.0

**Comment by brandxn-dp** [comment]
Having the same issues. MMM-Gestures wasn't working so I did a fresh install and now I get a black screen and this is what the logs say: 

28.02.2023 17:18.02.821] [ERROR] App threw an error during load
0|mm     | [28.02.2023 17:18.02.824] [ERROR] Error: No native build was found for platform=linux arch=arm runtime=electron abi=106 uv=1 armv=default libc=glibc node=16.14.2 electron=19.1.0
0|mm     |     loaded from: /home/pi/MagicMirror/modules/MMM-Gestures/node_modules/@serialport/bindings-cpp
0|mm     |     at load.path (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/node-gyp-build/index.js:60:9)
0|mm     |     at load (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/node-gyp-build/index.js:22:30)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/@serialport/bindings-cpp/dist/load-bindings.js:10:46)
0|mm     |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|mm     |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
0|mm     |     at Module.load (node:internal/modules/cjs/loader:988:32)
0|mm     |     at Module._load (node:internal/modules/cjs/loader:829:12)
0|mm     |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|mm     |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|mm     |     at require (node:internal/modules/cjs/helpers:102:18)
0|mm     | [28.02.2023 17:18.02.827] [ERROR] Whoops! There was an uncaught exception...
0|mm     | [28.02.2023 17:18.02.838] [ERROR] 
0|mm     | Error: No native build was found for platform=linux arch=arm runtime=electron abi=106 uv=1 armv=default libc=glibc node=16.14.2 electron=19.1.0
0|mm     |     loaded from: /home/pi/MagicMirror/modules/MMM-Gestures/node_modules/@serialport/bindings-cpp
0|mm     |     at load.path (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/node-gyp-build/index.js:60:9)
0|mm     |     at load (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/node-gyp-build/index.js:22:30)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Gestures/node_modules/@serialport/bindings-cpp/dist/load-bindings.js:10:46)
0|mm     |     at Module._compile (node:internal/modules/cjs/loader:1118:14)
0|mm     |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
0|mm     |     at Module.load (node:internal/modules/cjs/loader:988:32)
0|mm     |     at Module._load (node:internal/modules/cjs/loader:829:12)
0|mm     |     at c._load (node:electron/js2c/asar_bundle:5:13343)
0|mm     |     at Module.require (node:internal/modules/cjs/loader:1012:19)
0|mm     |     at require (node:internal/modules/cjs/helpers:102:18)
0|mm     | [28.02.2023 17:18.02.839] [ERROR] 
0|mm     | MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm     | [28.02.2023 17:18.02.840] [ERROR] 
0|mm     | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
